### ISSUE TITLE
Unable to import module 'process_cert_manager_mail': No module named urllib3

### ISSUE THREAD

**Issue by mvayngrib** [ImmobilienScout24/aws-cf-verified-ssl-certificate#7]
i'm probably doing something silly :)

this is my SSLCertificate resource from my serverless.yml (i'm using the Serverless framework):

```yaml
    SSLCertificate:
      Type: "AWS::CloudFormation::Stack"
      Properties:
        Parameters:
          domain: ${self:custom.domain}
          hostedZoneName: ${self:custom.hostedZoneName}    # your hosted domain
        TemplateURL: "https://s3-eu-west-1.amazonaws.com/is24-infrastructure-public/cloudformation/verified-ssl-certificate/ssl-certificate.template.yaml"
```

if you want to try out exactly what i'm deploying, see: https://github.com/mvayngrib/ssltest
edit domain and hostedDomainZone in serverless.yml and run `serverless deploy`
